- name: Make sure the CA certificates are available
  apt:
    pkg: ca-certificates
    state: present

- name: Add Barma apt repository
  apt_repository: repo='deb [arch=amd64] https://apt.2ndquadrant.com/ {{ ansible_lsb.codename }}-2ndquadrant main' state=present
  register: add_barman_repo

- name: Add Barman apt key
  apt_key: url=https://apt.2ndquadrant.com/site/keys/9904CD4BD6BAF0C3.asc state=present

- name: Update package list
  apt: update_cache=yes
  when: add_barman_repo

- name: Install Barman
  apt:
    name: "barman"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"

- name: Create Barman home directory
  file:
    path: '{{ barman_home }}'
    owner: "{{ barman_user }}"
    group: "{{ barman_user }}"
    mode: 0750
    state: directory

- name: Create Barman log directory
  file:
    path: '{{ barman_log_directory }}'
    owner: "{{ barman_user }}"
    group: "{{ barman_user }}"
    mode: 0750
    state: directory
