# For more information to customize kindly refer. https://github.com/weareinteractive/ansible-apt
---
- hosts: all
  become: yes
  roles:
   - weareinteractive.apt
  vars:
   apt_cache_valid_time: 7200
   apt_unattended_upgrades_blacklist:
    - postgresql-9.6
    - postgresql-9.6-plproxy
    - postgresql-contrib-9.6
    - postgresql-server-dev-9.6
    - rabbitmq-server
    - riak
    - riak-cs
    - zookeeper
   # Some Relevent default variabls.
   # enable unattended-upgrades
   apt_unattended_upgrades: yes
   # Do “apt-get update” automatically every n-days (0=disable)
   apt_update_package_lists: 0
   # Do “apt-get upgrade –download-only” every n-days (0=disable)
   apt_download_upgradeable_packages: 0
   # Do “apt-get autoclean” every n-days (0=disable)
   apt_auto_clean_interval: 0
   # Send email to this address for problems or packages upgrades
   apt_mails: ['devops@dimagi.com']
   # Set this value to "true" to get emails only on errors. Default is to always send a mail
   apt_unattended_upgrades_notify_error_only: false

  tasks:
    - name: Create a cron job to execute unattended-upgrades every week on Monday.
      cron:
        name: run unattended-upgrades on monday
        weekday: 1
        user: root
        job: "unattended-upgrades -v"