---
- hosts: all
  become: yes
  roles:
   - weareinteractive.apt
  vars:
   apt_cache_valid_time: 7200
   apt_unattended_upgrades_blacklist:
    - postgresql-9.6
    - postgresql-9.6-plproxy
    - postgresql-contrib-9.6
    - postgresql-server-dev-9.6
    - rabbitmq-server
    - riak
    - riak-cs
    - zookeeper
